openapi: "3.0.3"

info:
  title: "purchase-backend API"
  version: "1.0.0"

paths:
  "/priceAssessment":
    get:
      summary: "メッセージ取得"
      description: "メッセージを取得します"
      responses:
        "200":
          description: "Success operation"
          content:
            application/json:
              schema:
                type: string
                example: "Hello World!!"